env:
  global:
    - CC_TEST_REPORTER_ID=63f4a04100c58fe144558c9ae7b58efd8b0f15e8c3c9b71876c3a4f87b2b3e6f
language: node_js
node_js:
  - '9'
sudo: required
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - 'npm test'
after_success:
  - 'cat ./coverage/lcov.info | coveralls'
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
